version: '3.8'

services:
  mongo:
    image: mongo:7
    container_name: db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./data/mongo:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet mongodb://localhost:27017/${MONGODB_DATABASE}
      interval: 5s
      timeout: 10s
      retries: 5

  api:
    depends_on:
      mongo:
        condition: service_healthy
    build: ./api-server
    image: api_image
    container_name: api_1
    command: bash -c "npm start"
    ports:
      - "8080:8080"
    volumes:
      - ./api-server:/data/app
    environment:
      MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@db:27017/${MONGODB_DATABASE}?authSource=admin
      #                     👆 dùng `db` vì container name là db

  frontend:
    build: ./frontend-react
    image: frontend_image
    container_name: frontend_1
    command: bash -c "npm start"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-react:/data/app
